### ISSUE TITLE
trash empty panics when emptying trashed files from mounted drive

### ISSUE THREAD

**Issue by m4rch3n1ng** [oberblastmeister/trashy#89]
## issue

i have a drive mounted on `/mnt/drive`, using `trash empty --all` correctly shows me the trashed files, but confirming `"y"` on the prompt panics

running the same command (`trash-empty`) with `trash-cli` prompts me to delete the trash from `/mnt/drive/.Trash-1000/` and then correctly empties the trash

## stacktrace

```
thread 'main' panicked at 'assertion failed: file.exists()', /home/may/.cargo/registry/src/github.com-1ecc6299db9ec823/trash-2.1.5/src/freedesktop.rs:238:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

<details>

<summary>running with RUST_BACKTRACE=1 gives the exact same message, but gives a stack backtrace with RUST_BACKTRACE=full</summary>

```
thread 'main' panicked at 'assertion failed: file.exists()', /home/may/.cargo/registry/src/github.com-1ecc6299db9ec823/trash-2.1.5/src/freedesktop.rs:238:9
stack backtrace:
   0:     0x55aabd23626a - <unknown>
   1:     0x55aabd253e9e - <unknown>
   2:     0x55aabd233465 - <unknown>
   3:     0x55aabd236035 - <unknown>
   4:     0x55aabd2376bf - <unknown>
   5:     0x55aabd2373fb - <unknown>
   6:     0x55aabd237dc9 - <unknown>
   7:     0x55aabd237b22 - <unknown>
   8:     0x55aabd23671c - <unknown>
   9:     0x55aabd237872 - <unknown>
  10:     0x55aabd03da83 - <unknown>
  11:     0x55aabd03db1d - <unknown>
  12:     0x55aabd06a574 - <unknown>
  13:     0x55aabd058361 - <unknown>
  14:     0x55aabd06ac6b - <unknown>
  15:     0x55aabd06aa05 - <unknown>
  16:     0x55aabd05850f - <unknown>
  17:     0x55aabd06b068 - <unknown>
  18:     0x55aabd054a73 - <unknown>
  19:     0x55aabd06fb79 - <unknown>
  20:     0x55aabd22d3ec - <unknown>
  21:     0x55aabd06de15 - <unknown>
  22:     0x7f6104344790 - <unknown>
  23:     0x7f610434484a - __libc_start_main
  24:     0x55aabd03e0b5 - <unknown>
  25:                0x0 - <unknown>
```

</details>

### info

```
$ trash --version
trashy 2.0.0
```

running on arch, installed via the AUR

**Comment by m4rch3n1ng** [comment]
decided to look into why exactly this was happening and it somehow stopped happening? i installed it via cargo to debug and found out that the AUR version is outdated, but when i reinstalled from the AUR it just worked again i think.
